# Generated by Django 4.2.10 on 2024-08-11 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('pass_score', models.IntegerField(default=50)),
                ('max_score', models.IntegerField(default=100)),
                ('duration', models.CharField(default='00:60:00', max_length=25)),
                ('number_questions', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('answer_3', models.TextField()),
                ('answer_4', models.TextField()),
                ('correct_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex1_data.exams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.BooleanField(default=False)),
                ('correct_num', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('user_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex1_data.userexams')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuizlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex1_data.exams')),
                ('quizlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex1_data.quizlets')),
            ],
        ),
    ]
