# Generated by Django 4.2.10 on 2024-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlets',
            name='type',
            field=models.CharField(default='single', max_length=15),
        ),
    ]
