# Generated by Django 4.2.10 on 2024-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_data', '0002_quizlets_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlets',
            name='group',
            field=models.TextField(blank=True, default=''),
        ),
    ]
