# Generated by Django 4.2.15 on 2024-08-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_data', '0003_quizlets_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlets',
            name='group',
        ),
        migrations.RemoveField(
            model_name='quizlets',
            name='type',
        ),
    ]
